version: '3'
services:
  react-app:
    container_name: act-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src/:/app/src/
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host
